### ISSUE TITLE
Permission denied on install.js

### ISSUE THREAD

**Issue by calebeaires** [alejonext/NativeAdmob#1]
On npm install I get this error

![captura de tela 2015-06-01 as 14 52 35](https://cloud.githubusercontent.com/assets/794195/7919340/fa7e253c-086d-11e5-86f0-99a90e2e334a.png)

**Comment by calebeaires** [comment]
Some news on this issue?

**Comment by alejonext** [comment]
It is a permissions problem. And remember now the plugin is in beta.
